version: "3"

services:
  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.1
    ports:
      - 5601:5601

volumes:
  es-data:
